src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements \Symfony\Component\Security\Core\User\UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isAdmin;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToMany(targetEntity=Interet::class, inversedBy="users")
     */
    private $interests;

    /**
     * @ORM\OneToMany(targetEntity=Vehicule::class, mappedBy="user")
     */
    private $vehicules;

    /**
     * @ORM\OneToMany(targetEntity=TrajetFavoris::class, mappedBy="user")
     */
    private $favs;

    /**
     * @ORM\ManyToMany(targetEntity=Trajet::class, mappedBy="covoitureur")
     */
    private $mesTrajets;


    public function __construct()
    {
        $this->interests = new ArrayCollection();
        $this->vehicules = new ArrayCollection();
        $this->favs = new ArrayCollection();
        $this->mesTrajets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        if ($this->isAdmin){
            $roles[] = 'ROLE_ADMIN';
        }
        if (!$this->vehicules->isEmpty()){
            $roles[] = 'ROLE_CONDUCTOR';
        }
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getIsAdmin(): ?bool
    {
        return $this->isAdmin;
    }

    public function setIsAdmin(bool $isAdmin): self
    {
        $this->isAdmin = $isAdmin;

        return $this;
    }

    /**
     * @return Collection|Interet[]
     */
    public function getInterests(): Collection
    {
        return $this->interests;
    }

    public function addInterest(Interet $interest): self
    {
        if (!$this->interests->contains($interest)) {
            $this->interests[] = $interest;
        }
        return $this;
    }

    /**
     * @return Collection|Interet[]
     */
    public function getMesTrajets(): Collection
    {
        return $this->interests;
    }

    public function addMesTrajet(Trajet $mesTrajet): self
    {
        if (!$this->mesTrajets->contains($mesTrajet)) {
            $this->mesTrajets[] = $mesTrajet;
        }
        return $this;
    }

    /**
     * @return Collection|Vehicule[]
     */
    public function getVehicules(): Collection
    {
        return $this->vehicules;
    }

    public function addVehicule(Vehicule $vehicule): self
    {
        if (!$this->vehicules->contains($vehicule)) {
            $this->vehicules[] = $vehicule;
            $vehicule->setUser($this);
        }

        return $this;
    }

    public function removeInterest(Interet $interest): self
    {
        $this->interests->removeElement($interest);

        return $this;
    }

    public function removeMesTrajet(Trajet $mesTrajet): self
    {
        $this->mesTrajets->removeElement($mesTrajet);

        return $this;
    }

    public function removeVehicule(Vehicule $vehicule): self
    {
        if ($this->vehicules->removeElement($vehicule)) {
            // set the owning side to null (unless already changed)
            if ($vehicule->getUser() === $this) {
                $vehicule->setUser(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection|TrajetFavoris[]
     */
    public function getFavs(): Collection
    {
        return $this->favs;
    }

    public function addFav(TrajetFavoris $fav): self
    {
        if (!$this->favs->contains($fav)) {
            $this->favs[] = $fav;
            $fav->setUser($this);
        }

        return $this;
    }

    public function removeFav(TrajetFavoris $fav): self
    {
        if ($this->favs->removeElement($fav)) {
            // set the owning side to null (unless already changed)
            if ($fav->getUser() === $this) {
                $fav->setUser(null);
            }
        }

        return $this;
    }
}

templates/userPage/userPage.html.twig
{% extends 'base.html.twig' %}

{% from "form/inscription.html.twig" import inscription %}
{% from "form/updateVehicule.html.twig" import updateVehicule %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block nav %}
    {{ parent() }}
{% endblock %}

{% block body %}
    <section class="projects-section signup-section h-100 d-flex" style="color:white" id="profile">

{#        <div class="container d-flex h-100">#}

            <div class="row justify-content-around align-items-center w-100">

                <div class="col-sm-3 border border-white text-center p-2">
                    <h1>Mes informations</h1>
                    <div class="text-left p-3">
                        <p><b>Nom : </b> {{ infoUser.prenom }}</p>
                        <p><b>Prénom : </b>{{ infoUser.nom }}</p>
                        <p><b>Date de naissance : </b>{{ infoUser.dateNaissance | date("d/m/Y") }}</p>
                        <p><b>Adresse mail : </b>{{ infoUser.email }}</p>
                    </div>

                    {% if (app.user.id is same as(infoUser.id)) or is_granted('ROLE_ADMIN') %}
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#updateUser">
                        Modifier
                    </button>
                    {% endif %}

                    <div class="modal fade" id="updateUser" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="color:black">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Informations actuelles</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {{ inscription(form) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 border border-white text-center p-2">
                    <h1>Vos intérêts</h1>
                    <form class="form-group" id="form-Interet" method="POST" action="{{ url('user_updateInteret') }}">
                        <div class="overflow-auto h-50">
                            {% for info in infoInteret %}
                                <div data-toggle="tooltip" data-placement="left" title="{{ info.descriptif }}">
                                    <input class="form-check-input" type="checkbox" value ="{{ info.id }}"
                                            name="{{ info.id }}"
                                            {% if info in infoUser.interests %} checked {% endif %}
                                            {% if app.user.id is not same as(infoUser.id) %}disabled{% endif %}
                                    />
                                    <label class="form-check-label" style="color:white" for="{{ info.nom }}">{{ info.nom }}</label>
                                </div>
                            {% endfor %}
                        </div>
                        {% if (app.user.id is same as(infoUser.id)) or is_granted('ROLE_ADMIN') %}
                            <button type="submit" class="btn btn-primary btn-sm mt-5">Enregistrer</button>
                        {% endif %}
                    </form>
                </div>
                <div class="col-sm-3 border border-white text-center p-2 m-2">
                    <h1>Vos véhicule</h1>
                    {% if infoVehicule is empty %}
                        Vous n'avez enregistré aucun véhicule !
                    {% else %}
                        <div class="text-left m-2 overflow-auto">
                            {% set j = 1 %}
                            {% for infoV in infoVehicule %}
                                    <p>Véhicule {{ j }} :</p>
                                    <b>Marque : </b>{{ infoV.marque }} </br>
                                    <b>Model : </b>{{ infoV.model }} </br>
                                    <b>Consommation : </b>{{ infoV.consommation }} </br>
                                    <b>Immatriculation : </b>{{ infoV.immatriculation }} </br>
                                    <b>Nombres de place (conducteur inclu) : </b>{{ infoV.nbPlaces }} </br>
                                {% set j = j+1 %}

                                {% if (app.user.id is same as(infoUser.id)) or is_granted('ROLE_ADMIN') %}
                                    <button type="button" class="btn btn-primary m-3 p-2" data-toggle="modal" data-target="#updateVehicule{{ infoV.id }}">
                                        Modifier
                                    </button>
                                {% endif %}

                                <div class="modal fade" id="updateVehicule{{ infoV.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="color:black">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Informations actuelles</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                {{ updateVehicule(infoV) }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if (app.user.id is same as(infoUser.id)) or is_granted('ROLE_ADMIN') %}
                        <button type="button" class="btn btn-primary m-3 p-2" data-toggle="modal" data-target="#createVehicule">
                            Créer
                        </button>
                        <div class="modal fade" id="createVehicule" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="color:black">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Ajouter un véhicule</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        {{ updateVehicule() }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}


                </div>
                <div class="col-sm-5 border border-white text-center p-2">
                    <h1>Vos trajets favoris</h1>
                    <div class="text-left p-2">
                        {% set i = 1 %}
                        {% for info in infoTrajetFav %}
                        <p>
                            Trajet {{ i }}: </br>
                            <b>Adresse de départ : </b> {{ info.lieuDepart.adresse }} {{ info.lieuDepart.codePostal }} {{ info.lieuDepart.ville }} </br>
                            <b>Adresse d'arrivé : </b>{{ info.lieuArrivee.adresse }} {{ info.lieuArrivee.codePostal }} {{ info.lieuArrivee.ville }} </br>
                            {% set i = i+1 %}
                        </p>
                        {% endfor %}
                    </div>

                </div>

            </div>
{#        </div>#}
    </section>
{% endblock %}